=== SomodyMate/IGRYHL_XMLGyak/IGRYHL_1004/IGRYHL_orarend.dtd
<!ELEMENT IGRYHL_orarend (ora)>
    !ELEMENT ora (szak, kurzus_név, oktató, időpont, helyszín)>
        <!ELEMENT targy ANY>
        <!ELEMENT idopont (kezdet, vég, nap)>
            <!ELEMENT nap ANY>
            <!ELEMENT tol ANY>
            <!ELEMENT ig ANY>
        <!ELEMENT helyszin ANY>
        <!ELEMENT oktato ANY>
        <!ELEMENT szak ANY>


<!ATTLIST ora id ID #REQUIRED>
<!ATTLIST ora tipus (elmelet|gyakorlat) "elmélet">

=== SomodyMate/IGRYHL_XMLGyak/09.27/IGRYHL_orarend.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE IGRYHL_orarend SYSTEM "IGRYHL_orarend.dtd">

<IGRYHL_orarend>
    <ora id="1" tipus="elmelet">
        <targy> Adatkezelés XML-ben </targy>
        <idopont>
            <nap> Kedd </nap>
            <tol> 12:00 </tol>
            <ig>  14:00 </ig>
        </idopont>
        <helyszin> A1 XXXII. </helyszin>
        <oktato> Dr. Bednarik László </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>
    <ora id="2" tipus="gyakorlat">
        <targy> Adatkezelés XML-ben </targy>
        <idopont>
            <nap> Szerda </nap>
            <tol> 12:00 </tol>
            <ig>  14:00 </ig>
        </idopont>
        <helyszin> In 101 </helyszin>
        <oktato> Dr. Bednarik László </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>
    <ora id="3" tipus="elmélet">
        <targy> Vállalati Információs Rendszerek </targy>
        <idopont>
            <nap> Szerda </nap>
            <tol> 14:00 </tol>
            <ig>  16:00 </ig>
        </idopont>
        <helyszin> In 103 </helyszin>
        <oktato> Dr. Sasvári Péter </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>
    <ora id="4" tipus="gyakorlat">
        <targy> Vállalati Információs Rendszerek </targy>
        <idopont>
            <nap> Szerda </nap>
            <tol> 18:00 </tol>
            <ig>  20:00 </ig>
        </idopont>
        <helyszin> In 103 </helyszin>
        <oktato> Dr. Sasvári Péter </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>
    <!-- A dokumentumot a codebeautify.org-on alakítottam táblázattá. -->
</IGRYHL_orarend>
